<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-RG3O8VV" failures="0" tests="1" name="Default test" time="0.066" errors="0" timestamp="2023-12-14T14:17:05 IST">
  <testcase classname="com.framework.base.BaseTest" name="@BeforeSuite initialize" time="0.014">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Invalid escape sequence (valid ones are  \b  \t  \n  \f  \r  \&amp;quot;  \&amp;apos;  \\ )
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Invalid escape sequence (valid ones are  \b  \t  \n  \f  \r  \"  \'  \\ )

at com.framework.dataaccess.ExcelUtil.initializeExcel(ExcelUtil.java:24)
at com.framework.base.BaseTest.initialize(BaseTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:376)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite initialize -->
  <testcase classname="com.framework.base.BaseTest" name="@BeforeMethod launchBrowser" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod launchBrowser -->
  <testcase classname="com.framework.base.BaseTest" name="@BeforeMethod launchApplication" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod launchApplication -->
  <testcase classname="com.framework.base.BaseTest" name="@AfterMethod closeBrowser" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod closeBrowser -->
  <testcase classname="com.orangehrm.tests.LoginTest" name="verifyLoginWithValidCredentials" time="0.0">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="com.orangehrm.tests.LoginTest" name="verifyCopyRightText" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCopyRightText -->
  <testcase classname="com.orangehrm.tests.LoginTest" name="verifyloginWithBlankPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyloginWithBlankPassword -->
  <testcase classname="com.orangehrm.tests.LoginTest" name="verifyLoginWithInvalidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
</testsuite> <!-- Default test -->
